# Generated by Django 3.1.1 on 2020-09-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article',
            field=models.CharField(default='qwe', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date_time_posting',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('a', 'awaiting moderation'), ('r', 'rejected'), ('p', 'published')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='qwe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(limit_choices_to=5, to='blog.Topic'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='qwesad', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='sad', max_length=100),
            preserve_default=False,
        ),
    ]
