# Generated by Django 3.1.1 on 2020-09-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200915_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_time_posting',
        ),
    ]
