# Generated by Django 3.1.1 on 2020-09-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200915_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article',
            new_name='title',
        ),
    ]
