# Generated by Django 3.1.1 on 2020-09-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200915_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
