# Generated by Django 3.1.1 on 2020-09-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200926_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_change_status', 'Can change post status'), ('can_see_non_published_posts', 'Can see non published posts'))},
        ),
    ]
