# Generated by Django 3.1.1 on 2020-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200926_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
