# Generated by Django 3.1.1 on 2020-09-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
